apiVersion: v1
kind: Pod
metadata:
    name: sqlredis
    labels:
        hareta: redis
spec:
    containers:
        - name: redis
          image: bitnami/redis:latest
          resources:
              limits:
                  memory: "128Mi"
                  cpu: "500m"
          env:
              - name: REDIS_PASSWORD
                value: "ngogianhan7203"
          ports:
              - containerPort: 6379
        - name: mysql
          image: bitnami/mysql:latest
          env:
              - name: MYSQL_ROOT_PASSWORD
                value: "07022003"
          ports:
              - containerPort: 3306
