apiVersion: v1
kind: Pod
metadata:
    namespace: frontend
    name: nginx
    labels:
        app: my-app
spec:
    hostname: my-nginx
    subdomain: my-nginx-1
    containers:
        - name: nginx
          image: nginx
          ports:
              - containerPort: 80
